# Generated by Django 3.1 on 2020-08-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to='quote_dash.User'),
        ),
    ]
